apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - mysql-deployment.yaml
  - mysql-service.yaml

images:
  - name: identityorg/cerberus
    newTag: latest

commonAnnotations:
  env: staging

namespace: cerberus-release

configMapGenerator:
  - name: cerberus
    behavior: replace
    files:
      - cerberus.yaml