kind: Service
apiVersion: v1
metadata:
  name: cerberus
  namespace: default
  labels:
    app: cerberus
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: cerberus
  type: ClusterIP
