apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cerberus-deployment.yaml
  - cerberus-service.yaml
  - cerberus-ingress.yaml
  - cerberus-namespace.yaml

images:
  - name: identityorg/cerberus
    newTag: edge

commonAnnotations:
  env: staging

namespace: cerberus-dev

configMapGenerator:
  - name: cerberus
    files:
      - cerberus.yaml