// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"net/http"
	"strings"
	"time"
)

// AddClaimToScope defines model for AddClaimToScope.
type AddClaimToScope struct {

	// Claim id to add
	ClaimId int `json:"claim_id"`
}

// ApiError defines model for ApiError.
type ApiError struct {

	// Error code
	ErrorCode string `json:"error_code"`

	// Detail description
	Message string `json:"message"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {

	// The new password to set.
	NewPassword string `json:"new_password"`

	// The old or existing password
	OldPassword string `json:"old_password"`
}

// Claim defines model for Claim.
type Claim struct {

	// A short dercription about the claim.
	Description *string `json:"description,omitempty"`

	// Internal identifier of the claim
	Id int `json:"id"`

	// A alphanumeric name, to represent claim name in OAuth2 claim.
	Name string `json:"name"`
}

// ClaimPage defines model for ClaimPage.
type ClaimPage struct {
	// Embedded fields due to inline allOf schema

	// an array of claims
	Claims []Claim `json:"claims"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// Page defines model for Page.
type Page struct {

	// Page number of the response chunk
	PageNumber int `json:"page_number"`

	// Total available pages
	PageTotal int `json:"page_total"`
}

// RegenerateCredentials defines model for RegenerateCredentials.
type RegenerateCredentials struct {

	// Wheather to regenerate the client id too
	RefreshId *bool `json:"refresh_id,omitempty"`
}

// Scope defines model for Scope.
type Scope struct {

	// A short dercription about the scope.
	Description *string `json:"description,omitempty"`

	// Internal identifier of the scope
	Id int `json:"id"`

	// Scope name. alphanumeric characters only.
	Name string `json:"name"`
}

// ScopePage defines model for ScopePage.
type ScopePage struct {
	// Embedded fields due to inline allOf schema

	// An array of scopes as returned in search result or so.
	Scopes []Scope `json:"scopes"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// Secret defines model for Secret.
type Secret struct {

	// Suitable algorithm for the key. allowed values are all supported `JWS` and `JWK` algorithms.
	Algorithm string `json:"algorithm"`

	// Date when the secret expires
	ExpiresAt time.Time `json:"expires_at"`

	// Date when the key was issued
	IssuedAt time.Time `json:"issued_at"`

	// usage of the key
	KeyUsage string `json:"key_usage"`
}

// SecretChannel defines model for SecretChannel.
type SecretChannel struct {

	// Suitable algorithm for the key. allowed values are all supported `JWS` and `JWK` algorithms.
	Algorithm string `json:"algorithm"`

	// Identifier of the `SecretChannel`.
	Id int `json:"id"`

	// usage of the key
	KeyUsage string `json:"key_usage"`

	// A friendly name for the key channel
	Name string `json:"name"`

	// A list of secrets associates with channel
	Secrets []Secret `json:"secrets"`

	// How mant days the key will be valid, when generated or renewed
	ValidityDay int `json:"validity_day"`
}

// SecretChannelPage defines model for SecretChannelPage.
type SecretChannelPage struct {
	// Embedded fields due to inline allOf schema

	// An array of `SecretChannelSummary` objects
	Channels []SecretChannelSummary `json:"channels"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// SecretChannelSummary defines model for SecretChannelSummary.
type SecretChannelSummary struct {

	// Suitable algorithm for the key. allowed values are all supported `JWS` and `JWK` algorithms.
	Algorithm string `json:"algorithm"`

	// Identifier of the `SecretChannel`.
	Id int `json:"id"`

	// usage of the key
	KeyUsage string `json:"key_usage"`

	// A friendly name for the key channel
	Name string `json:"name"`
}

// ServiceProvider defines model for ServiceProvider.
type ServiceProvider struct {
	// Embedded struct due to allOf(#/components/schemas/ServiceProviderInfo)
	ServiceProviderInfo
	// Embedded struct due to allOf(#/components/schemas/ServiceProviderConfig)
	ServiceProviderConfig
	// Embedded struct due to allOf(#/components/schemas/ServiceProviderSummary)
	ServiceProviderSummary
}

// ServiceProviderConfig defines model for ServiceProviderConfig.
type ServiceProviderConfig struct {

	// Default requested Authentication Context Class Reference values. Array of strings that specifies the default acr values that the OP is being requested to use for processing requests from this Client, with the values appearing in order of preference. The Authentication Context Class satisfied by the authentication performed is returned as the acr Claim Value in the issued ID Token. The acr Claim is requested as a Voluntary Claim by this parameter. The acr_values_supported discovery element contains a list of the supported acr values supported by this server. Values specified in the acr_values request parameter or an individual acr Claim request override these default values.
	DefaultAcrValues *[]string `json:"default_acr_values,omitempty"`

	// Default Maximum Authentication Age. Specifies that the End-User MUST be actively authenticated if the End-User was authenticated longer ago than the specified number of seconds. The max_age request parameter overrides this default value. If omitted, no default Maximum Authentication Age is specified.
	DefaultMaxAge *int `json:"default_max_age,omitempty"`

	// JSON array containing a list of the OAuth 2.0 Grant Types that the Client is declaring that it will restrict itself to using. The Grant Type values used by
	//
	// OpenID Connect are:
	// 1. authorization_code: The Authorization Code Grant Type described in OAuth 2.0 Section 4.1.
	// 1. implicit: The Implicit Grant Type described in OAuth 2.0 Section 4.2.
	// 1. refresh_token: The Refresh Token Grant Type described in OAuth 2.0 Section 6.
	//
	// The following table lists the correspondence between response_type values that the Client will use and grant_type values that MUST be included in the registered grant_types list:
	//
	// 1. code: authorization_code
	// 1. id_token: implicit
	// 1. token id_token: implicit
	// 1. code id_token: authorization_code, implicit
	// 1. code token: authorization_code, implicit
	// 1. code token id_token: authorization_code, implicit
	//
	// If omitted, the default is that the Client will use only the authorization_code Grant Type.
	GrantTypes []string `json:"grant_types"`

	// JWE alg algorithm [JWA] REQUIRED for encrypting the ID Token issued to this Client. If this is requested, the response will be signed then encrypted, with the result being a Nested JWT, as defined in [JWT]. The default, if omitted, is that no encryption is performed.
	IdTokenEncryptedResponseAlg *string `json:"id_token_encrypted_response_alg,omitempty"`

	// JWE enc algorithm [JWA] REQUIRED for encrypting the ID Token issued to this Client. If id_token_encrypted_response_alg is specified, the default for this value is A128CBC-HS256. When id_token_encrypted_response_enc is included, id_token_encrypted_response_alg MUST also be provided.
	IdTokenEncryptedResponseEnc *string `json:"id_token_encrypted_response_enc,omitempty"`

	// JWS alg algorithm [JWA] REQUIRED for signing UserInfo Responses. If this is specified, the response will be JWT [JWT] serialized, and signed using JWS. The default, if omitted, is for the UserInfo Response to return the Claims as a UTF-8 encoded JSON object using the application/json content-type.
	IdTokenSignedResponseAlg *string `json:"id_token_signed_response_alg,omitempty"`

	// Client's JSON Web Key Set [JWK] document, passed by value. The semantics of the jwks parameter are the same as the jwks_uri parameter, other than that the JWK Set is passed by value, rather than by reference. This parameter is intended only to be used by Clients that, for some reason, are unable to use the jwks_uri parameter, for instance, by native applications that might not have a location to host the contents of the JWK Set. If a Client can use jwks_uri, it MUST NOT use jwks. One significant downside of jwks is that it does not enable key rotation (which jwks_uri does, as described in Section 10 of OpenID Connect Core 1.0 [OpenID.Core]). The jwks_uri and jwks parameters MUST NOT be used together.
	Jwks *string `json:"jwks,omitempty"`

	// URL for the Client's JSON Web Key Set [JWK] document. If the Client signs requests to the Server, it contains the signing key(s) the Server uses to validate signatures from the Client. The JWK Set MAY also contain the Client's encryption keys(s), which are used by the Server to encrypt responses to the Client. When both signing and encryption keys are made available, a use (Key Use) parameter value is REQUIRED for all keys in the referenced JWK Set to indicate each key's intended usage. Although some algorithms allow the same key to be used for both signatures and encryption, doing so is NOT RECOMMENDED, as it is less secure. The JWK x5c parameter MAY be used to provide X.509 representations of keys provided. When used, the bare key values MUST still be present and MUST match those in the certificate.
	JwksUri *string `json:"jwks_uri,omitempty"`

	// Array of Redirection URI values used by the Client. One of these registered Redirection URI values MUST exactly match the redirect_uri parameter value used in each Authorization Request, with the matching performed as described in Section 6.2.1 of [RFC3986] (Simple String Comparison).
	RedirectUris []string `json:"redirect_uris"`

	//  JWE [JWE] alg algorithm [JWA] the RP is declaring that it may use for encrypting Request Objects sent to the OP. This parameter SHOULD be included when symmetric encryption will be used, since this signals to the OP that a client_secret value needs to be returned from which the symmetric key will be derived, that might not otherwise be returned. The RP MAY still use other supported encryption algorithms or send unencrypted Request Objects, even when this parameter is present. If both signing and encryption are requested, the Request Object will be signed then encrypted, with the result being a Nested JWT, as defined in [JWT]. The default, if omitted, is that the RP is not declaring whether it might encrypt any Request Objects.
	RequestObjectEncryptionAlg *string `json:"request_object_encryption_alg,omitempty"`

	// JWE enc algorithm [JWA] the RP is declaring that it may use for encrypting Request Objects sent to the OP. If request_object_encryption_alg is specified, the default for this value is A128CBC-HS256. When request_object_encryption_enc is included, request_object_encryption_alg MUST also be provided.
	RequestObjectEncryptionEnc *string `json:"request_object_encryption_enc,omitempty"`

	// JWS [JWS] alg algorithm [JWA] that MUST be used for signing Request Objects sent to the OP. All Request Objects from this Client MUST be rejected, if not signed with this algorithm. Request Objects are described in Section 6.1 of OpenID Connect Core 1.0 [OpenID.Core]. This algorithm MUST be used both when the Request Object is passed by value (using the request parameter) and when it is passed by reference (using the request_uri parameter). Servers SHOULD support RS256. The value none MAY be used. The default, if omitted, is that any algorithm supported by the OP and the RP MAY be used.
	RequestObjectSigningAlg *string `json:"request_object_signing_alg,omitempty"`

	// Array of request_uri values that are pre-registered by the RP for use at the OP. Servers MAY cache the contents of the files referenced by these URIs and not retrieve them at the time they are used in a request. OPs can require that request_uri values used be pre-registered with the require_request_uri_registration discovery parameter.
	// If the contents of the request file could ever change, these URI values SHOULD include the base64url encoded SHA-256 hash value of the file contents referenced by the URI as the value of the URI fragment. If the fragment value used for a URI changes, that signals the server that its cached value for that URI with the old fragment value is no longer valid.
	RequestUris *[]string `json:"request_uris,omitempty"`

	// Boolean value specifying whether the auth_time Claim in the ID Token is REQUIRED. It is REQUIRED when the value is true. (If this is false, the auth_time Claim can still be dynamically requested as an individual Claim for the ID Token using the claims request parameter described in Section 5.5.1 of OpenID Connect Core 1.0 [OpenID.Core].) If omitted, the default value is false.
	RequireAuthTime *bool `json:"require_auth_time,omitempty"`

	// Approved oauth scopes for the service providers
	Scope []string `json:"scope"`

	// Requested Client Authentication method for the Token Endpoint. The options are client_secret_post, client_secret_basic, client_secret_jwt, private_key_jwt, and none, as described in Section 9 of OpenID Connect Core 1.0 [OpenID.Core]. Other authentication methods MAY be defined by extensions. If omitted, the default is client_secret_basic -- the HTTP Basic Authentication Scheme specified in Section 2.3.1 of OAuth 2.0 [RFC6749].
	TokenEndpointAuthMethod *string `json:"token_endpoint_auth_method,omitempty"`

	// JWS [JWS] alg algorithm [JWA] that MUST be used for signing the JWT [JWT] used to authenticate the Client at the Token Endpoint for the private_key_jwt and client_secret_jwt authentication methods. All Token Requests using these authentication methods from this Client MUST be rejected, if the JWT is not signed with this algorithm. Servers SHOULD support RS256. The value none MUST NOT be used. The default, if omitted, is that any algorithm supported by the OP and the RP MAY be used.
	TokenEndpointAuthSigningAlg *string `json:"token_endpoint_auth_signing_alg,omitempty"`

	// JWE [JWE] alg algorithm [JWA] REQUIRED for encrypting UserInfo Responses. If both signing and encryption are requested, the response will be signed then encrypted, with the result being a Nested JWT, as defined in [JWT]. The default, if omitted, is that no encryption is performed.
	UserinfoEncryptedResponseAlg *string `json:"userinfo_encrypted_response_alg,omitempty"`

	// JWE enc algorithm [JWA] REQUIRED for encrypting UserInfo Responses. If userinfo_encrypted_response_alg is specified, the default for this value is A128CBC-HS256. When userinfo_encrypted_response_enc is included, userinfo_encrypted_response_alg MUST also be provided.
	UserinfoEncryptedResponseEnc *string `json:"userinfo_encrypted_response_enc,omitempty"`

	// JWS alg algorithm [JWA] REQUIRED for signing UserInfo Responses. If this is specified, the response will be JWT [JWT] serialized, and signed using JWS. The default, if omitted, is for the UserInfo Response to return the Claims as a UTF-8 encoded JSON object using the application/json content-type.
	UserinfoSignedResponseAlg *string `json:"userinfo_signed_response_alg,omitempty"`
}

// ServiceProviderCredentials defines model for ServiceProviderCredentials.
type ServiceProviderCredentials struct {

	// Client identifier
	ClientId string `json:"client_id"`

	// Client secret
	ClientSecret string `json:"client_secret"`
}

// ServiceProviderInfo defines model for ServiceProviderInfo.
type ServiceProviderInfo struct {

	// Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type MUST only register URLs using the https scheme as redirect_uris; they MUST NOT use localhost as the hostname. Native Clients MUST only register redirect_uris using custom URI schemes or URLs using the http: scheme with localhost as the hostname. Authorization Servers MAY place additional constraints on Native Clients. Authorization Servers MAY reject Redirection URI values using the http scheme, other than the localhost case for Native Clients. The Authorization Server MUST verify that all the registered redirect_uris conform to these constraints. This prevents sharing a Client ID across different types of Clients.
	ApplicationType string `json:"application_type"`

	// URL of the home page of the Client. The value of this field MUST point to a valid Web page. If present, the server SHOULD display this URL to the End-User in a followable fashion. If desired, representation of this Claim in different languages and scripts is represented as described in Section 2.1.
	ClientUri *string `json:"client_uri,omitempty"`

	// Array of e-mail addresses of people responsible for this Client. This might be used by some providers to enable a Web user interface to modify the Client information.
	Contacts *[]string `json:"contacts,omitempty"`

	// URI using the https scheme that a third party can use to initiate a login by the RP, as specified in Section 4 of OpenID Connect Core 1.0 [OpenID.Core]. The URI MUST accept requests via both GET and POST. The Client MUST understand the login_hint and iss parameters and SHOULD support the target_link_uri parameter.
	InitiateLoginUri *string `json:"initiate_login_uri,omitempty"`

	// URL that references a logo for the Client application. If present, the server SHOULD display this image to the End-User during approval. The value of this field MUST point to a valid image file. If desired, representation of this Claim in different languages and scripts is represented as described in Section 2.1.
	LogoUri *string `json:"logo_uri,omitempty"`

	// URL that the Relying Party Client provides to the End-User to read about the how the profile data will be used. The value of this field MUST point to a valid web page. The OpenID Provider SHOULD display this URL to the End-User if it is given. If desired, representation of this Claim in different languages and scripts is represented as described in Section 2.1.
	PolicyUri *string `json:"policy_uri,omitempty"`

	// URL that the Relying Party Client provides to the End-User to read about the Relying Party's terms of service. The value of this field MUST point to a valid web page. The OpenID Provider SHOULD display this URL to the End-User if it is given. If desired, representation of this Claim in different languages and scripts is represented as described in Section 2.1.
	TosUri *string `json:"tos_uri,omitempty"`
}

// ServiceProviderSummary defines model for ServiceProviderSummary.
type ServiceProviderSummary struct {

	// A description of the service provider
	Description *string `json:"description,omitempty"`

	// Identifier of the provider.
	Id int `json:"id"`

	// Service provider name
	Name string `json:"name"`

	// Wheather the `ServiceProvider` is a public SP, which does not require authentication.
	Public bool `json:"public"`
}

// ServiceProviderSummaryPage defines model for ServiceProviderSummaryPage.
type ServiceProviderSummaryPage struct {
	// Embedded fields due to inline allOf schema

	// An array of service provider summary in one page.
	ServiceProviders []ServiceProviderSummary `json:"service_providers"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// StatusUpdate defines model for StatusUpdate.
type StatusUpdate struct {

	// New status to change to.
	Active bool `json:"active"`
}

// User defines model for User.
type User struct {
	// Embedded struct due to allOf(#/components/schemas/UserName)
	UserName
	// Embedded struct due to allOf(#/components/schemas/UserProfile)
	UserProfile
	// Embedded struct due to allOf(#/components/schemas/UserContact)
	UserContact
	// Embedded struct due to allOf(#/components/schemas/UserSummary)
	UserSummary
}

// UserAddress defines model for UserAddress.
type UserAddress struct {

	// Country name component.
	Country *string `json:"country,omitempty"`

	// Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
	Formatted *string `json:"formatted,omitempty"`

	// City or locality component.
	Locality *string `json:"locality,omitempty"`

	// Zip code or postal code component.
	PostalCode *string `json:"postal_code,omitempty"`

	// State, province, prefecture, or region component.
	Region *string `json:"region,omitempty"`

	// Full street address component, which MAY include house number, street name, Post Office Box, and multi-line extended street address information. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
	StreetAddress *string `json:"street_address,omitempty"`
}

// UserContact defines model for UserContact.
type UserContact struct {

	// End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7.
	Email *string `json:"email,omitempty"`

	// True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating.
	EmailVerified *bool `json:"email_verified,omitempty"`

	// End-User's preferred telephone number. E.164 [E.164] is RECOMMENDED as the format of this Claim, for example, +1 (425) 555-1212 or +56 (2) 687 2400. If the phone number contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966 [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678.
	PhoneNumber *string `json:"phone_number,omitempty"`

	// User at the time the verification was performed. The means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be represented in RFC 3966 format.
	PhoneNumberVerified *bool `json:"phone_number_verified,omitempty"`
}

// UserName defines model for UserName.
type UserName struct {

	// Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters.
	FamilyName *string `json:"family_name,omitempty"`

	// Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters.
	GivenName *string `json:"given_name,omitempty"`

	// Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.
	MiddleName *string `json:"middle_name,omitempty"`

	// End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.
	Name *string `json:"name,omitempty"`

	// Casual name of the End-User that may or may not be the same as the given_name. For instance, a nickname value of Mike might be returned alongside a given_name value of Michael.
	Nickname *string `json:"nickname,omitempty"`

	// Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique.
	PreferredUsername *string `json:"preferred_username,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {

	// End-User's preferred postal address. The value of the address member is a JSON [RFC4627] structure containing some or all of the members defined in Section 5.1.1.
	Address *UserAddress `json:"address,omitempty"`

	// End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates.
	Birthdate *openapi_types.Date `json:"birthdate,omitempty"`

	// End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither of the defined values are applicable.
	Gender *string `json:"gender,omitempty"`

	// End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase and an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well.
	Locale *string `json:"locale,omitempty"`

	// URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.
	Picture *string `json:"picture,omitempty"`

	// URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.
	Profile *string `json:"profile,omitempty"`

	// URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an organization that the End-User is affiliated with.
	Website *string `json:"website,omitempty"`

	// String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
	Zoneinfo *string `json:"zoneinfo,omitempty"`
}

// UserRecoverPassword defines model for UserRecoverPassword.
type UserRecoverPassword struct {

	// Email id of the user to confirm with user store
	Email string `json:"email"`

	// Username of the user
	Username string `json:"username"`
}

// UserResetPassword defines model for UserResetPassword.
type UserResetPassword struct {

	// One time password received through initiation process
	Otp string `json:"otp"`

	// Username of the user
	Username string `json:"username"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {

	// User is active or inactive
	Active bool `json:"active"`

	// User is blocked by invalid attempt
	Blocked bool `json:"blocked"`

	// Email address
	Email string `json:"email"`

	// Internal identifier of the user
	Id int `json:"id"`

	// Login username
	Username string `json:"username"`
}

// UserSummaryPage defines model for UserSummaryPage.
type UserSummaryPage struct {
	// Embedded fields due to inline allOf schema

	// A collection of users
	Users []UserSummary `json:"users"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// UnAuthorized defines model for UnAuthorized.
type UnAuthorized ApiError

// GetClaimsParams defines parameters for GetClaims.
type GetClaimsParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateClaimJSONBody defines parameters for CreateClaim.
type CreateClaimJSONBody Claim

// FindClaimByNameParams defines parameters for FindClaimByName.
type FindClaimByNameParams struct {

	// name of the claim
	Name string `json:"name"`
}

// UpdateClaimJSONBody defines parameters for UpdateClaim.
type UpdateClaimJSONBody Claim

// GetScopesParams defines parameters for GetScopes.
type GetScopesParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateScopeJSONBody defines parameters for CreateScope.
type CreateScopeJSONBody Scope

// FindScopeByNameParams defines parameters for FindScopeByName.
type FindScopeByNameParams struct {

	// scope name
	Name string `json:"name"`
}

// UpdateScopeJSONBody defines parameters for UpdateScope.
type UpdateScopeJSONBody Scope

// AddClaimToScopeJSONBody defines parameters for AddClaimToScope.
type AddClaimToScopeJSONBody AddClaimToScope

// GetSecretChannelsParams defines parameters for GetSecretChannels.
type GetSecretChannelsParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateSecretChannelJSONBody defines parameters for CreateSecretChannel.
type CreateSecretChannelJSONBody SecretChannel

// FindSecretChannelByAlgouseParams defines parameters for FindSecretChannelByAlgouse.
type FindSecretChannelByAlgouseParams struct {

	// algorithm of the channel
	Algo string `json:"algo"`

	// usage of the secret channel
	Use string `json:"use"`
}

// FindSecretChannelByNameParams defines parameters for FindSecretChannelByName.
type FindSecretChannelByNameParams struct {

	// name of the secret channel
	Name string `json:"name"`
}

// GetServiceProvidersParams defines parameters for GetServiceProviders.
type GetServiceProvidersParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateServiceProviderJSONBody defines parameters for CreateServiceProvider.
type CreateServiceProviderJSONBody ServiceProvider

// FindServiceProviderParams defines parameters for FindServiceProvider.
type FindServiceProviderParams struct {

	// service provider name
	Name *string `json:"name,omitempty"`

	// service provider client id
	ClientId *string `json:"client_id,omitempty"`
}

// PatchServiceProviderJSONBody defines parameters for PatchServiceProvider.
type PatchServiceProviderJSONBody ServiceProvider

// UpdateServiceProviderJSONBody defines parameters for UpdateServiceProvider.
type UpdateServiceProviderJSONBody ServiceProvider

// GenerateCredentialsJSONBody defines parameters for GenerateCredentials.
type GenerateCredentialsJSONBody RegenerateCredentials

// UpdateServiceProviderStatusJSONBody defines parameters for UpdateServiceProviderStatus.
type UpdateServiceProviderStatusJSONBody StatusUpdate

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody User

// FindUserParams defines parameters for FindUser.
type FindUserParams struct {

	// Username of the user
	Username *string `json:"username,omitempty"`

	// email of the user
	Email *string `json:"email,omitempty"`
}

// InitiatePasswordRecoveryJSONBody defines parameters for InitiatePasswordRecovery.
type InitiatePasswordRecoveryJSONBody UserRecoverPassword

// ResetUserPasswordJSONBody defines parameters for ResetUserPassword.
type ResetUserPasswordJSONBody UserResetPassword

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody User

// ChangeUserPasswordJSONBody defines parameters for ChangeUserPassword.
type ChangeUserPasswordJSONBody ChangePasswordRequest

// UpdateUserStatusJSONBody defines parameters for UpdateUserStatus.
type UpdateUserStatusJSONBody StatusUpdate

// CreateClaimRequestBody defines body for CreateClaim for application/json ContentType.
type CreateClaimJSONRequestBody CreateClaimJSONBody

// UpdateClaimRequestBody defines body for UpdateClaim for application/json ContentType.
type UpdateClaimJSONRequestBody UpdateClaimJSONBody

// CreateScopeRequestBody defines body for CreateScope for application/json ContentType.
type CreateScopeJSONRequestBody CreateScopeJSONBody

// UpdateScopeRequestBody defines body for UpdateScope for application/json ContentType.
type UpdateScopeJSONRequestBody UpdateScopeJSONBody

// AddClaimToScopeRequestBody defines body for AddClaimToScope for application/json ContentType.
type AddClaimToScopeJSONRequestBody AddClaimToScopeJSONBody

// CreateSecretChannelRequestBody defines body for CreateSecretChannel for application/json ContentType.
type CreateSecretChannelJSONRequestBody CreateSecretChannelJSONBody

// CreateServiceProviderRequestBody defines body for CreateServiceProvider for application/json ContentType.
type CreateServiceProviderJSONRequestBody CreateServiceProviderJSONBody

// PatchServiceProviderRequestBody defines body for PatchServiceProvider for application/json ContentType.
type PatchServiceProviderJSONRequestBody PatchServiceProviderJSONBody

// UpdateServiceProviderRequestBody defines body for UpdateServiceProvider for application/json ContentType.
type UpdateServiceProviderJSONRequestBody UpdateServiceProviderJSONBody

// GenerateCredentialsRequestBody defines body for GenerateCredentials for application/json ContentType.
type GenerateCredentialsJSONRequestBody GenerateCredentialsJSONBody

// UpdateServiceProviderStatusRequestBody defines body for UpdateServiceProviderStatus for application/json ContentType.
type UpdateServiceProviderStatusJSONRequestBody UpdateServiceProviderStatusJSONBody

// CreateUserRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// InitiatePasswordRecoveryRequestBody defines body for InitiatePasswordRecovery for application/json ContentType.
type InitiatePasswordRecoveryJSONRequestBody InitiatePasswordRecoveryJSONBody

// ResetUserPasswordRequestBody defines body for ResetUserPassword for application/json ContentType.
type ResetUserPasswordJSONRequestBody ResetUserPasswordJSONBody

// UpdateUserRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// ChangeUserPasswordRequestBody defines body for ChangeUserPassword for application/json ContentType.
type ChangeUserPasswordJSONRequestBody ChangeUserPasswordJSONBody

// UpdateUserStatusRequestBody defines body for UpdateUserStatus for application/json ContentType.
type UpdateUserStatusJSONRequestBody UpdateUserStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List All claims
	// (GET /v1/api/claims)
	GetClaims(ctx echo.Context, params GetClaimsParams) error
	// Create a Claim
	// (POST /v1/api/claims)
	CreateClaim(ctx echo.Context) error
	// find claim by name
	// (GET /v1/api/claims/find)
	FindClaimByName(ctx echo.Context, params FindClaimByNameParams) error
	// Delete a Claim
	// (DELETE /v1/api/claims/{id})
	DeleteClaim(ctx echo.Context, id int) error
	// Get a Claim
	// (GET /v1/api/claims/{id})
	GetClaim(ctx echo.Context, id int) error
	// Update a Claim
	// (PUT /v1/api/claims/{id})
	UpdateClaim(ctx echo.Context, id int) error
	// List All scopes
	// (GET /v1/api/scopes)
	GetScopes(ctx echo.Context, params GetScopesParams) error
	// Create a Scope
	// (POST /v1/api/scopes)
	CreateScope(ctx echo.Context) error
	// Used to find a scope with name
	// (GET /v1/api/scopes/find)
	FindScopeByName(ctx echo.Context, params FindScopeByNameParams) error
	// Delete a Scope
	// (DELETE /v1/api/scopes/{id})
	DeleteScope(ctx echo.Context, id int) error
	// Get a Scope
	// (GET /v1/api/scopes/{id})
	GetScope(ctx echo.Context, id int) error
	// Update a Scope
	// (PUT /v1/api/scopes/{id})
	UpdateScope(ctx echo.Context, id int) error
	// Add a claim to a scope
	// (POST /v1/api/scopes/{id}/claim)
	AddClaimToScope(ctx echo.Context, id int) error
	// Remove one claim from scope
	// (DELETE /v1/api/scopes/{id}/claim/{claimId})
	RemoveClaimFromScope(ctx echo.Context, id int, claimId int) error
	// List All secretchannels
	// (GET /v1/api/secretchannels)
	GetSecretChannels(ctx echo.Context, params GetSecretChannelsParams) error
	// Create a SecretChannel
	// (POST /v1/api/secretchannels)
	CreateSecretChannel(ctx echo.Context) error
	// Find secret channel by algo and use
	// (GET /v1/api/secretchannels/find/algouse)
	FindSecretChannelByAlgouse(ctx echo.Context, params FindSecretChannelByAlgouseParams) error
	// Fins secret by name
	// (GET /v1/api/secretchannels/find/name)
	FindSecretChannelByName(ctx echo.Context, params FindSecretChannelByNameParams) error
	// Delete a SecretChannel
	// (DELETE /v1/api/secretchannels/{id})
	DeleteSecretChannel(ctx echo.Context, id int) error
	// Get a SecretChannel
	// (GET /v1/api/secretchannels/{id})
	GetSecretChannel(ctx echo.Context, id int) error
	// Renew the secret of the channel
	// (POST /v1/api/secretchannels/{id})
	RenewSecretChannel(ctx echo.Context, id int) error
	// List All serviceproviders
	// (GET /v1/api/serviceproviders)
	GetServiceProviders(ctx echo.Context, params GetServiceProvidersParams) error
	// Create a ServiceProvider
	// (POST /v1/api/serviceproviders)
	CreateServiceProvider(ctx echo.Context) error
	// find sp by client id or name
	// (GET /v1/api/serviceproviders/find)
	FindServiceProvider(ctx echo.Context, params FindServiceProviderParams) error
	// Delete a ServiceProvider
	// (DELETE /v1/api/serviceproviders/{id})
	DeleteServiceProvider(ctx echo.Context, id int) error
	// Get a ServiceProvider
	// (GET /v1/api/serviceproviders/{id})
	GetServiceProvider(ctx echo.Context, id int) error
	// Patch service provider
	// (PATCH /v1/api/serviceproviders/{id})
	PatchServiceProvider(ctx echo.Context, id int) error
	// Update a ServiceProvider
	// (PUT /v1/api/serviceproviders/{id})
	UpdateServiceProvider(ctx echo.Context, id int) error
	// Retrieves the existing credentials
	// (GET /v1/api/serviceproviders/{id}/credentials)
	GetCredentials(ctx echo.Context, id int) error
	// Generate the credentials
	// (POST /v1/api/serviceproviders/{id}/credentials)
	GenerateCredentials(ctx echo.Context, id int) error
	// Activate or Deactivate a service provider
	// (POST /v1/api/serviceproviders/{id}/status)
	UpdateServiceProviderStatus(ctx echo.Context, id int) error
	// List All users
	// (GET /v1/api/users)
	GetUsers(ctx echo.Context, params GetUsersParams) error
	// Create a User
	// (POST /v1/api/users)
	CreateUser(ctx echo.Context) error
	// find user by username or email id
	// (GET /v1/api/users/find)
	FindUser(ctx echo.Context, params FindUserParams) error
	// Initiate Password Recovery
	// (POST /v1/api/users/recover/password)
	InitiatePasswordRecovery(ctx echo.Context) error
	// Reset password, after recovery
	// (PUT /v1/api/users/recover/password)
	ResetUserPassword(ctx echo.Context) error
	// Delete a User
	// (DELETE /v1/api/users/{id})
	DeleteUser(ctx echo.Context, id int) error
	// Get a User
	// (GET /v1/api/users/{id})
	GetUser(ctx echo.Context, id int) error
	// Update a User
	// (PUT /v1/api/users/{id})
	UpdateUser(ctx echo.Context, id int) error
	// Change Password
	// (POST /v1/api/users/{id}/password)
	ChangeUserPassword(ctx echo.Context, id int) error
	// Update status
	// (POST /v1/api/users/{id}/status)
	UpdateUserStatus(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClaims converts echo context to params.
func (w *ServerInterfaceWrapper) GetClaims(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClaimsParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetClaims(ctx, params)
	return err
}

// CreateClaim converts echo context to params.
func (w *ServerInterfaceWrapper) CreateClaim(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateClaim(ctx)
	return err
}

// FindClaimByName converts echo context to params.
func (w *ServerInterfaceWrapper) FindClaimByName(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindClaimByNameParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindClaimByName(ctx, params)
	return err
}

// DeleteClaim converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteClaim(ctx, id)
	return err
}

// GetClaim converts echo context to params.
func (w *ServerInterfaceWrapper) GetClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetClaim(ctx, id)
	return err
}

// UpdateClaim converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateClaim(ctx, id)
	return err
}

// GetScopes converts echo context to params.
func (w *ServerInterfaceWrapper) GetScopes(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetScopesParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetScopes(ctx, params)
	return err
}

// CreateScope converts echo context to params.
func (w *ServerInterfaceWrapper) CreateScope(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateScope(ctx)
	return err
}

// FindScopeByName converts echo context to params.
func (w *ServerInterfaceWrapper) FindScopeByName(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindScopeByNameParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindScopeByName(ctx, params)
	return err
}

// DeleteScope converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteScope(ctx, id)
	return err
}

// GetScope converts echo context to params.
func (w *ServerInterfaceWrapper) GetScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetScope(ctx, id)
	return err
}

// UpdateScope converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateScope(ctx, id)
	return err
}

// AddClaimToScope converts echo context to params.
func (w *ServerInterfaceWrapper) AddClaimToScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddClaimToScope(ctx, id)
	return err
}

// RemoveClaimFromScope converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveClaimFromScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// ------------- Path parameter "claimId" -------------
	var claimId int

	err = runtime.BindStyledParameter("simple", false, "claimId", ctx.Param("claimId"), &claimId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter claimId: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RemoveClaimFromScope(ctx, id, claimId)
	return err
}

// GetSecretChannels converts echo context to params.
func (w *ServerInterfaceWrapper) GetSecretChannels(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSecretChannelsParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSecretChannels(ctx, params)
	return err
}

// CreateSecretChannel converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSecretChannel(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateSecretChannel(ctx)
	return err
}

// FindSecretChannelByAlgouse converts echo context to params.
func (w *ServerInterfaceWrapper) FindSecretChannelByAlgouse(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindSecretChannelByAlgouseParams
	// ------------- Required query parameter "algo" -------------

	err = runtime.BindQueryParameter("form", true, true, "algo", ctx.QueryParams(), &params.Algo)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter algo: %s", err))
	}

	// ------------- Required query parameter "use" -------------

	err = runtime.BindQueryParameter("form", true, true, "use", ctx.QueryParams(), &params.Use)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter use: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindSecretChannelByAlgouse(ctx, params)
	return err
}

// FindSecretChannelByName converts echo context to params.
func (w *ServerInterfaceWrapper) FindSecretChannelByName(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindSecretChannelByNameParams
	// ------------- Required query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, true, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindSecretChannelByName(ctx, params)
	return err
}

// DeleteSecretChannel converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSecretChannel(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteSecretChannel(ctx, id)
	return err
}

// GetSecretChannel converts echo context to params.
func (w *ServerInterfaceWrapper) GetSecretChannel(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetSecretChannel(ctx, id)
	return err
}

// RenewSecretChannel converts echo context to params.
func (w *ServerInterfaceWrapper) RenewSecretChannel(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RenewSecretChannel(ctx, id)
	return err
}

// GetServiceProviders converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceProviders(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServiceProvidersParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetServiceProviders(ctx, params)
	return err
}

// CreateServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceProvider(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateServiceProvider(ctx)
	return err
}

// FindServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) FindServiceProvider(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindServiceProviderParams
	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", ctx.QueryParams(), &params.Name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "client_id", ctx.QueryParams(), &params.ClientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter client_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindServiceProvider(ctx, params)
	return err
}

// DeleteServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteServiceProvider(ctx, id)
	return err
}

// GetServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetServiceProvider(ctx, id)
	return err
}

// PatchServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) PatchServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchServiceProvider(ctx, id)
	return err
}

// UpdateServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateServiceProvider(ctx, id)
	return err
}

// GetCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCredentials(ctx, id)
	return err
}

// GenerateCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GenerateCredentials(ctx, id)
	return err
}

// UpdateServiceProviderStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceProviderStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateServiceProviderStatus(ctx, id)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsers(ctx, params)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// FindUser converts echo context to params.
func (w *ServerInterfaceWrapper) FindUser(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params FindUserParams
	// ------------- Optional query parameter "username" -------------

	err = runtime.BindQueryParameter("form", true, false, "username", ctx.QueryParams(), &params.Username)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter username: %s", err))
	}

	// ------------- Optional query parameter "email" -------------

	err = runtime.BindQueryParameter("form", true, false, "email", ctx.QueryParams(), &params.Email)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter email: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindUser(ctx, params)
	return err
}

// InitiatePasswordRecovery converts echo context to params.
func (w *ServerInterfaceWrapper) InitiatePasswordRecovery(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InitiatePasswordRecovery(ctx)
	return err
}

// ResetUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ResetUserPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ResetUserPassword(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// ChangeUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangeUserPassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ChangeUserPassword(ctx, id)
	return err
}

// UpdateUserStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUserStatus(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET("/v1/api/claims", wrapper.GetClaims)
	router.POST("/v1/api/claims", wrapper.CreateClaim)
	router.GET("/v1/api/claims/find", wrapper.FindClaimByName)
	router.DELETE("/v1/api/claims/:id", wrapper.DeleteClaim)
	router.GET("/v1/api/claims/:id", wrapper.GetClaim)
	router.PUT("/v1/api/claims/:id", wrapper.UpdateClaim)
	router.GET("/v1/api/scopes", wrapper.GetScopes)
	router.POST("/v1/api/scopes", wrapper.CreateScope)
	router.GET("/v1/api/scopes/find", wrapper.FindScopeByName)
	router.DELETE("/v1/api/scopes/:id", wrapper.DeleteScope)
	router.GET("/v1/api/scopes/:id", wrapper.GetScope)
	router.PUT("/v1/api/scopes/:id", wrapper.UpdateScope)
	router.POST("/v1/api/scopes/:id/claim", wrapper.AddClaimToScope)
	router.DELETE("/v1/api/scopes/:id/claim/:claimId", wrapper.RemoveClaimFromScope)
	router.GET("/v1/api/secretchannels", wrapper.GetSecretChannels)
	router.POST("/v1/api/secretchannels", wrapper.CreateSecretChannel)
	router.GET("/v1/api/secretchannels/find/algouse", wrapper.FindSecretChannelByAlgouse)
	router.GET("/v1/api/secretchannels/find/name", wrapper.FindSecretChannelByName)
	router.DELETE("/v1/api/secretchannels/:id", wrapper.DeleteSecretChannel)
	router.GET("/v1/api/secretchannels/:id", wrapper.GetSecretChannel)
	router.POST("/v1/api/secretchannels/:id", wrapper.RenewSecretChannel)
	router.GET("/v1/api/serviceproviders", wrapper.GetServiceProviders)
	router.POST("/v1/api/serviceproviders", wrapper.CreateServiceProvider)
	router.GET("/v1/api/serviceproviders/find", wrapper.FindServiceProvider)
	router.DELETE("/v1/api/serviceproviders/:id", wrapper.DeleteServiceProvider)
	router.GET("/v1/api/serviceproviders/:id", wrapper.GetServiceProvider)
	router.PATCH("/v1/api/serviceproviders/:id", wrapper.PatchServiceProvider)
	router.PUT("/v1/api/serviceproviders/:id", wrapper.UpdateServiceProvider)
	router.GET("/v1/api/serviceproviders/:id/credentials", wrapper.GetCredentials)
	router.POST("/v1/api/serviceproviders/:id/credentials", wrapper.GenerateCredentials)
	router.POST("/v1/api/serviceproviders/:id/status", wrapper.UpdateServiceProviderStatus)
	router.GET("/v1/api/users", wrapper.GetUsers)
	router.POST("/v1/api/users", wrapper.CreateUser)
	router.GET("/v1/api/users/find", wrapper.FindUser)
	router.POST("/v1/api/users/recover/password", wrapper.InitiatePasswordRecovery)
	router.PUT("/v1/api/users/recover/password", wrapper.ResetUserPassword)
	router.DELETE("/v1/api/users/:id", wrapper.DeleteUser)
	router.GET("/v1/api/users/:id", wrapper.GetUser)
	router.PUT("/v1/api/users/:id", wrapper.UpdateUser)
	router.POST("/v1/api/users/:id/password", wrapper.ChangeUserPassword)
	router.POST("/v1/api/users/:id/status", wrapper.UpdateUserStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9624cN7PgqxCzC8TGGY0utpXYHxY4iiw7chJLq8vnzbEFmermzDDuIfsj2ZInhoHz",
	"CucVz5MsWEWy2d3suciS4+zmT2L1kEWyWKw7i58GmZyVUjBh9ODZp4FiupRCM/jjXOxVZioV/4Pl9u9M",
	"CsOEsf+kZVnwjBouxebvWgr7TWdTNqP2X/9TsfHg2eB/bNbAN/FXvblX8gOlpBp8/vx5OMiZzhQvLZzB",
	"s8F+wZkwhGtSCULD2MRIQrOMaU3MlBHF/lUxbQa2v4NqB93L8/2C8tmZPM1kyeynJvS9PCeUZLaNhWhB",
	"aWg5HLCPdFYW0Ad+v+T54Nn21ufhoFSyZMpwxEj946fO1C1YjnPN88FwYOZ2EgMuDJswBbO1M+fKIvNt",
	"DepiODDc2MEHJ1IacjYvGRlLRdoLCiDl1e8sM4PPw0FAZnexgjD7C/E7Slyv9pKg1WUm8wTGADaB38Lg",
	"2iguJnbwGdOaThLdnjNDeUHij53uLWxEs6gBXyRWvD+lYsKOqdY3UuUnjhS6yycZNCSla+mppg8Ngt1c",
	"+rZdcGdTRgS7qaEZSTQzo8FwMJZqRs3g2SD0TqBKFvkS6LLIiVSEfeTacDEhEbQVRmhhszHcsLm2JFIt",
	"mSWRCFSdSTHmk0rBce9DYKNrF5KeSmVIzpT/SuiVrAycQhhllMJb6qQdCsOUoAXhOROGjzlTRI5rQImj",
	"NxwIOktxBEKLckpFNWOKZ8Q2GtqtVaxUTFtWhAiwPxAuyJHlhzu9823tAowJa+jF+bE7P7QojsaDZ28/",
	"pfhNF70DKghVis7twl2b4YAbhm0XsV/c6s9hQgAmzZx0at6LocN6Pl8MO3gu6cRtjyZU10xprOSM7B0f",
	"ppibR04TJRbSpahmVyzB9WwXgj96mghDZdNKfEgSB4A00tAicTbtZ0KvKS/oVcFgIXo5d49n2RggRQon",
	"bMIEU9SwfcWAqGmhU9Ta5GEgJKoyp8AwpCLA7TccLPsNzkQEsiHoFBsrpqcgzYyqWEfYxQ3ac3kzZdRM",
	"mcLT4qfvDiEKccskZY2pKykLRgVgKi3v0mhI4KtPvvvz6cXlnTEoUBPugkHppiBfyqBgJcB+Rk1WlU2p",
	"oplhShMpivmXMiMYZxkzgsnrpKoRmBG2wSNuKiVYbvmmZlRlU3sUq8JYMtVytCrDws1cxrDc3G7PsLoo",
	"YZliSc1Cwy/kA5uDkiFYAeRLSUmV4VlVUNU8abSYSMXNdGZJ/nTnye5gOPjA5pcVqk8DzScDTwGDnI1p",
	"VVj5ek0LnnMzv8zpPKmNRnA7hFNxA/wqtIE5Whr8wOaWmAp5w3JyTYvK7peyLQuiq7KUyrCcvH/15vQ9",
	"oQL+9fP7Go5OngP2seSK6UuawNhzyxlupkzgEUDsuQ6xepNTwzYMnyWVTa51xfIV4NttuaGaYIeV4Uf7",
	"0YYPn/0J/sDmdnNFNQOyg51jIosor+cA1gMMo42LF9bAYq9VgHS5j4Q36CVc3+C+6BcMpJXIGIfTwFBi",
	"SFrOGDHsY2vhzwY7W9s/bGztbGxvnW09ffZo6z8aWEr/3p6HPfdfb7CLv9ZhTQqtjqx63yCk96Ok2Lr7",
	"Y9Ovq48VZyIv5qiORxjyZJxaa6C+LryCW1Vq7M6DFVpaZpwapskNN9MI6mqCCgVGR1K1aaM9kZ/kDZlR",
	"YUhO57pmYbwoyBUj0HeI7M2rRzlqeoLdsBUcDX2MpzGrYaQg1Ei7Iya01MrBZktUiyY9nlazGVXz904X",
	"1uvtUhPIcnPIT/DuDKK1mXCNpAV81J7sp08XsOW68SIOCcz9SROMPa0pMBef74ZI/F78LbD+Flj//wqs",
	"FXl305q77elT1zxjx0pe8xydKTWDXsxCGx0PxVgu5YOtPvvgUVy3V2DXXX7q3ZK16w58IsLaGwCDlA7I",
	"aAVcuOkltnQmc1Y0XITDzghElyzjY2ulx45TTUqpNb8qUq4J4D2XNFOXeGZSTnVo431ALCd7lZnahWIY",
	"huxLYfkF2S+o1uSEjZliImPuEI7IXrDRgdasqkGNnytDzcNNhNBM+cMLrexvR8eEa3LFLGLrSRhJKo0U",
	"VyqZMa2j3zX698yUa4KxnSGqVhaeZw5lyaidEOGCSJXjeS6Vn/+InE3Z4rVqargec5aTqzmAps3WJVPW",
	"CGS5XUDwS1Bcsl0qBm/+aSdkZ2E/I0slh8/JmfzABM6ibguAPA6oJpT8UxaVMFTNXQuYCtdWRtEZM0wF",
	"EG6LL2t2mHOdyWum5oQVbAZ+ZykM5cIC9moqGM+hS7RD9Uc/pqVIO+A/XQO3x7lfXD2J4FIM07S6JRWE",
	"i5xf87yiRbTq4H+8ZkrxHPx9uqYaR2mxKtbhlW3d2JP+jH687AkmIfBf6Uc+q2ZtStibsBE5jYjYUeuB",
	"yDfONVPk1/PTM6tI08zwa1bMY+KwGBk3m9/YzWy0KKSYMEXoRFrozokRMFo7mzXLpMg1brNbTgq9Dnca",
	"t6qBuxE5HBM548awfEiEDL/2L95SYphNWuRNFBXm0n5PsJVXp0evnY7taM4exSbVgVuV7Iy2yEsLCmRM",
	"hOo6apuzrMCzDD9yg2aMYnb/M/tBs2KMPIOLCaKqhukJutJIy+/EO3FUMnH43B54Ydk7VezZO7E9CtFh",
	"QAQEDp8FRhG+k32ZNwbAtV/hSaiXdcoyaP54tD0C6HxWFjzjBmEeur/WgrSDkLwT3VguguBO8BMyljVg",
	"7o4sQiyEsbQKFuAZ1DC7WcjNMqkw4JED779i5oYxEYIgQAUdzu42EPbKMnOrl9VE02juTxMXWVHlNUdR",
	"bMK1YYrFPTVM7Jmd9faI4B519w0RnnsMedTDZ/jW96PtHP3WhTxMtF+/8cpDvBPx6Y3FKV+AbCmKWmg1",
	"gUe0sR5T9TO+ZCJT89Kw/DJQAC0Sis2rNwdWB4/0+bev3uxdkJOD/31+eHLwHOS7A+YDS140elEJKRVB",
	"0AMrg79jUTlshuS8k0PziZXIlreRMOVIVXCBA9Q9KHmNYvfVm7Ohlb05G3MXaHj76s3ZBbIVh/uh5fBh",
	"U/xGCBlWI+0CahWhx/7ox6c1CpL4ZCK7a3wu2deGLGhSIBofXONhtg33tnd+2P9xf+Mnax+PyJtpROk9",
	"67Td/MEfLp0MsApaaGl32OnGS9CLdLCUVk+X06qFZBFrZbo1UMiJT2xqEGYLWx3CfPXmDGnKqlScFvwP",
	"29TyR0eyIMfIqzeni4nO236d6aApYTVSxxx8hJyS87MXGz9YIpGWz4KcdjYODgo8o5WGRVyK1oaZ9wQs",
	"f7/5oFPZS5bGvtM4zBt2RX5mc3LKjF39zxckl1k1A/W9pNpJZ6exnEFMZ0atVqK9xmBHiXQeqjA0rK0d",
	"7PRu2+SyUrxuNiQSQ8qoZTl++erNzzARUKUbYw+JonWHqzlp2Ayx6o2Ea5iwmESGC1TpFQ1cPvKGIdKP",
	"nFlyoFqKIUy/EiBpnbnTtwDblQttqMjY0EIW1Gqd8T45DjTjk6nlQ4ZMqW1ACumUOiPJVGqXGYPbGfDq",
	"kAE0TL0oyaiASfkJDa3iBafv9dFZ+GVEjgRyWmuagr9Z3ghttXg5xg3z3JHb35iG2TFc9wc2J0oanOGD",
	"mynPpjUCbGPHiSMFxqst21t2gJYety8VI9ujLfIWfxjZDxcPkZwCYHvQmqSk64X5/TNywiwZ9JK7BdUl",
	"+fOTX8KxXJX8He8IQtxiU9fGrksqPAXrC3YhmHFA/Y4nfWDzB/ph1NSuA3qDT44abEpNpViwoFmQA2fR",
	"ofh17zdksW6g5moiEfeBzfUD/XBIcOuAonVtMLt5mCAWAysMq/LDg6C4kmYa1mN3qTUUDDCjOaszZ4aE",
	"Ai0+sKg91+xhdDyDUGrwcFoUCCzomO5452H9RoKhag01wmg2te2/i846+M5GZK8wU1lNpnisa2cjOipr",
	"1mSpPOIMdhJhpW47mosdklxaFGhpZ2+p8uRg/+jXXw9ePz94DkeCA+cqmLZWeVYpVm/gxydZhAO7lTVJ",
	"e4FJ/s/oydbT2tvkWIgcI2aCWMVtsZ1Rkl3ZDbDLcco7nBptnFjz2W12MfDLjJrMqlpSBwdIxpQBTmHS",
	"gkSxnCuWGXu6UpEb7206ce0saZyfHLZtvJi0LINCRqcbFkUPCJg5+0gzU8zDCmzHemIdGoNhuUBiadqK",
	"Lpc0UjsBJiRjBgdSH5PbHe2Mtu3k35682H/09IfdC/Lg1JoGjJwCysi+nJVUcS3Fw/WUecdeLlH4X9bE",
	"l1aPiNU93756c3CR1JLsuk6O08b6jM6DMy9STh1iyBFG2giQjuMKR8cdWXv609H5L88bRiJEL/V8NmNG",
	"8SxmFl7RQsrV3Bqt6MKyR67Q9Tg4S+rSyy5dTAh3VTCWa3dyg38PGCeyOzjgYfg4vJozxa/x0DSEMmgi",
	"N1yzGCQe3ZNjOKt4mMCCAyWk9sJFy4tYjVUqmMhJJYK+3MbskLBrJnwqS1uBcYcWZNAi/mtPfsvgao7z",
	"55ldNfFZHNcEeDMFCQ40CFvgpRAV8zaSephR3xlZyzy7h8NxOCYLD/AX22wLl9602BZPZHV7rQXH0WG/",
	"tfb21ZvTPm4U+ZSCzPWEvQy3e0XRadMOOAToitkGQI1jID9H/Y7aua4nN+pAtWeqh+9vr6zdOk5Z46Cx",
	"cDjSIYutdWK7xg95UFuBHSfzQ+AJAIy3OgclKgGgKTEfjpxaqD1LdyyOnCD5nfkgDhFSsFiBWYEV2JNd",
	"Y6IVwgB+b5dgan7rQS8iyCWqSLzM2Klpd7dUbCNSOdw0To4xyVozEqJgNVrstDKaTVnSVhvzAuIrQWlF",
	"mJpZHQYVSUuGygoldg0wZn4Uw2fwYV5r6lwQ6lcwIkfHGuw+FyzGdSTWh6TVWV7E4qH/ZdT1Etu52x51",
	"aKoOZIGjM7VkT4h26SSTVZFbiabcXZxhvXw/PUdYjkU5zVWz3ceVKoLr4/SnvY2dJ7tkSvXUEVyE4noS",
	"HVTDSM7d0Ohnv48VnTRsOv8h1hQxzcQ2xyVopygE7WTKXLDNywmNFOFyHxwPpwZgBKzLIm8PBzLRx5rA",
	"DlxfS7QbSSszvYQk1845+BEz8N2AKHTmsfj1Xmjo7wOdou2cDEbaiByahtEWuFdYklEVG5EHkcdtTAuN",
	"lNAZytJzMFHyuaAzntGimLcirY3YJPb0dnyYZc3a3J2Tbhwuyc6fjJ6sw9Afkj6Pf8AArHeUuAYxxJz1",
	"BLsqrfBlOZEWQT6j3i+xnWyg16IS77DNS8mFQWKZMTOViQSbk4B1J0lbwUfsFyaGiD9woFECyBLNVcvE",
	"Gnr7ZSmtpdX8dkU1z9off78xQ1Iqfk0Nu/zA5vgBmadg/V6np2uI5SOgfppanvayx2u7V3PCPhomtF3Y",
	"iCyI+CQWRzY2oNVPZ2fH5Ef40kLqaTZlM9aM2Psl7YweOeIMoUFrbe5+//jpRVIspnb73pQ1dE96d7l3",
	"Y8Sh9Nhz5uRck2gCLbX2G7a7QxY9G4ZqIQI+8Z65wA8069vn1RRHv0pnwizSIddTnlpeza+tQVWaKS7G",
	"cq2IYb+XoS/O1ROOWdOc/cvFDxdh907ihz14XbKrX2x7LllX0/pcNpnV7c8A6e944T3HC1vpqHEmUdsD",
	"7PWZixXSKxfdcj1r3lklfMRG5L3j/jx3WcMNaQCpvu2L0659X6wzupyZIrEG/F4Y7ufbXNFvDjCMJrwC",
	"AiHlNlXfgtt/0oLY02FnZLmTYgV1mZqpXNhW0ndNIJc4i/YoP3ORezsqar2Ynm/YVWgAvDbKDHchUqmw",
	"1Rt2FeKxNeGiypNKxAK2ATFdb9+S85Nf4r5TY0pNNGpWcDM1ott/oJndCJcWMqMFxGCd8Wj/jZdwX+Nk",
	"/QQTgzegu1lklTZyBjYgTgPcwYlpPvPTBNG1YB7N0EXskCgLmjFCa1rIpLDWPAc7XbRWsAgSKj79AZx4",
	"4m7erRB+jMqMOudpewLdrD0XjQTkXjPFx3On8RRFO9msie1MAt07H6Fm8dp9nEKxa9g6PUX/bgijHz4n",
	"NFNSa5LzMXgSDMEsNjkOs43uBNywK8jEt6tJXgtwR7o3+uwO0VTOsKyA/xAHeiO3hRULnBUuYocKs9Ww",
	"0VsA56aEaOfhmITc9MhB4fTQnOuyoC5R2E7DOVRDBiw4mjDDEEL/Y6qncMAPx9bUsgxs2ApIhgkGn0GN",
	"woKKSUUnLnSKOHBJYQ7EgrDazmg7qQFAuDszi5x9bGNGeWEPgmJa4y6WTJZFENscVucVnRrrXLsoRJQh",
	"AoHjYHNjoBxvwADiK0ScYWpsT5+RZCZzpNs6P7bmyWtm8wluuDWHCjnhoo+eDvs4noubmSlXOdyYmoeM",
	"EQifI3DIQJlwUXs+QTdOGqKP13J5o7sNtbssY6WpEyauOUXd/+XBGZDH8dHpGfaJjbBKWKQbb84gGqbc",
	"BbC5buSH2E8tkws8qlRNmLksuPjQdHMn6auQE9l/cJ2z1XkbNaJOtrJJmsJxjTPJZ5YXtE9lXiG3AucQ",
	"LdblDgh0zAv2TZ3jUhY8my/BNMZDCnBVHgP9Ogy786g7yAIlmeZRBY+pS/MolQSncU4NbQSf10XoTWC3",
	"tp87DF4/W53Xjl2AZsKv2bfFYo3UX2FfGv2/08QwNdN4mwJU1b+3ZZER0dHWV7Ad+u/ZrneHbq3iOtHf",
	"4SpTC+bt730mbvYtL6zTvrPnblR2OVR1VfBsUQEkvHnawPF7u8uUYF9yeuzT7kJWpQ/bNX2Ro3S1pHjH",
	"4Xq+m6ub2up7vrTAD/a6rGMLi2v9dO494jBwkU+gTrt6mZ+eq57L6v50pnxnV/S/9EqpoabS52VOTfJy",
	"MBTuYkRDs1DTsnmNHa6s9VTn8j+2Ib9mNx6okb4KopEr0JaDmKInyxVXvyBsW7+2NLoM9bbhMUrkldru",
	"o9q/UtsFl4VJjgUqQWt3mxxp54MeBOyhKZEok+nkxnfa3Vu1lmkpNVSOw04dOcb8L2TG4AYhcAzw2r09",
	"ebH/eHfn+wuijaoyUykW380DU8SlxzpQCKLhya4jmtsoSeJSErISxoqARpUBXL+xtND4DiY8N+3muD5X",
	"OLTxizXPAS/xR20UY+aSehw2KlG0nXd+fh23G/6A9+nDvifVl2g1bSgvqqIg1jgEhRonBKn72AH0eK8i",
	"uOQPaW1i36WgV6xwhqLTRfZ+CxnYs6owvIRLeYLpIdHMmhouMCPYDXwekdfuX2CLQZSp1gkYx4CkpYiM",
	"KsXxJqmplNi0nciYWQKjXJEH7wbv3ql378S7wUMgCtvH2oFuAtg0VIvD9rZxj9njt7qDeW4AGb7FEuw3",
	"iKMN6z94idfrpPKnBP5cDNJTVUeSG2rYEHkx3LqAIwinZoh1cmy/JcDb1JkkGWwUzm2A6KW7pQKfyTKV",
	"lmzwcvDQ98T6osdSG3I0HlsJ8qP8iOEBoJoN2DEIL+csb48X+w/+3yO+zz1M17P8rhlimbfzAwFumjyO",
	"2dParqNiv12CR5EzV/VyOCinUtQVRZs8Lvqp1a/DtNyAK8mGpm9qRA6ND7SBVdN0Y5KTF/vkyaOdHRAM",
	"9h8X0HNDlywjei4M/VhnJns/tmLFnFSlFHEYDwOgleD/qlzqBNdZpXVbZHyfrvHXQl8ncqMq1r5P/51u",
	"LZZMqSZXjAniAf0jSrbGbBkMLkZm1T/jfKIh/jJjVDSrUxgpPxA6HnM4JddWt2Kl89XpyifJQefWnG4o",
	"+I6NkkVRR9CDOdhKynMzd/kDtm8d/cXL/zC1q7m/bCPa49kNcasn6La2BLfh64YgS8hZafmAMH4bmV2+",
	"NmSs6IzdSPWBSDwB9nhBoYaJYlA+AguYcRGlv0OpJBdxsWQLBWLTeUnNA7ESQRtWMOjmWN6IHIy2dx+T",
	"t/C/C8wSCxdjfDgD+VnThMY7dO4gD8m/bZMHj3eePCRPnjzZ2N7Z3rFr/rcnu+TBzkOy+8P3ZOfx1lZI",
	"4YunEJXQEHXKztAZ9vFsAg2FVm2eWHtW7Vl89HR3193z2N29iHrhWUysYHfrsV/Bo8f/YB/N/3qy+/0P",
	"acmZZjlJ7veldNnE1zdDlO74u6PudtWhxDGEugyBIzRHSnaKVMQpWlEaT72fXNQbiT17zKOkSHrdU+7J",
	"mhOgmRqkPNaqSjamM17MLzsl1IYDcDOlfpjxPC9Y6pfUJ559SHwOp/TST3Cx9t2YZrfyF0B4oEHgF1Sj",
	"VgN/Nzn/iLyWxvFcLtBqyaoCbtENfSTG6h9w/zUoLjg6AIUgqZDxp3+A1eO0luBQD3k+2AulXEP10SXN",
	"WFQ0OXn04l1or/ul/Y1ESx9zdedrn4RB9L0utEFV7ZX+Cj/e8cpmNdC7WxrZK7QkYsF84mEx10Ca/hy4",
	"ND4ieTe2VoB/C8BZiNQFEWdO9Qeb0jez/M2iBet+zaMmULPNOYar8Zh/tNOF6ldQ2ymTCpvJtjYFBhiW",
	"aKlrZKW3ueYHHWuOasuaYY6tDXYX4dD0tf+zKLvqXt+vD8uIvGjceqfED1z7O37lH1gdVK1LcBVSTOAK",
	"Oo0Axt2yKWVFWlAm2FqHW02lMlNIFrZwg+RrVnziesrq24Neo5EkXFgbEl1ZeanJ71SwXILl+vsol77Q",
	"gNPdMcfSyh8MRoA3B2ccbT0IVGvz1iXcPfh/H5JNMFpvptwwIPhbaPY91lWySmCQZz2yznvnVo0WgEvN",
	"B9msVaZbvqfIxP723FBXXJkpOmxdHc3tje3vrYC2So9KzagjbTm4Hjoy2KGx8fWGXWlu2l//kIKBPbtQ",
	"Skd4XOYJ9X7L5gIX8DnXaj5sR6qoIIenR+SH3a3tZztbW4/J28PTI/vXf//nf9m/L8hvv/3228avv248",
	"f+4VK6DfOaPhhvvW1tbW0F/bj29Ycu1zxkbkLH6EJZRIsmCGMIZX+Lj2xUZjyYRaKrrroSNkEGCksSyo",
	"sZ2/0wQc8D49blyJDK/0o1vftv3darYwd7xrBVnEXJBrqgDWTAozRb3YYksjt4Zr31bjtUdbMFfKh35w",
	"N5vHNDPAMPFVK3sIwFMvlWJwld3VUcR8XGqQuzeq2Ce1F0eiC/YVm4SygNGVBrxy7TR9GvKux2zmhY39",
	"h78p4e/fRxUL4OqPcL4jJ1ISuX4uYHlVsH7/42LaxCZdyiQ/7h8//h5dJLuPdy9C9JUYOnFsmmti5qW7",
	"VORoeffR041tsleUU7qxA/S8++jpf//nf21HELDQmCCWzhTksaGdAQAebe/utiDYTwjCsbgAoSpLhNBy",
	"zVGSUz1FSRosRyY2zk9B11Qb+3sjsgcuOTkrqeFXHLywVvkZotYTqM6ViAAFDPaGCpdBk0kV5LcbXqpG",
	"ER2cR8uCZeLy/PQfjVA9d9ufTaXEPCKX2gOE5HQUNIftgDes6BHinlsuyI9rOBxQsLhublttW5COILxh",
	"MiJKeCEPGquh5Pj1yyF5dXzwEkTty8MXUeOHzaJCkFngM+saBRLdCDHXCekEPv3Inye8w+bv3dJ6GVNp",
	"ZEcB0764chSHcLf0hM8V8O4I36k5a3gd6oobRdXcDWLZj2g7tnr0qh6Jv2RLQtJF81Io1zX+6soQdQLI",
	"wrkEAbnaXMJAUpGrQvpj3x7fO8vjJGmIpetpwvmH5VClmlDh81O7RUatGBqPecHhQFtbJrmeWrR3oxig",
	"JcIlJN+KvPX/ukAfj/0TMpeuqGZNvauFidC8xVIOKqtEbB5TxcG63oPXhOjmL1Jf7okJK5KmRJ8j5ITB",
	"1eDj3oftmi9WNdINo3f58H7xcvf9au6LPj88OGB5SF2vXD4SlGhWM7Q/4aM2UrG+aydpO+Pce34i4EuT",
	"dwI451nvDbyfMM3MYiRrZjovHTYRKk15K3RCv/aQR8J5HeNdZPwa7mApqLTkNhrOFuozXwGldrIR0D6E",
	"LnpqwKWwdLO8omSB/iyN4eCqkNmHOriUomOeD57tPF51A/ryPALfyfz1CS5c25RTP8yrD45rYPkfF2i/",
	"WjNsVpokvIXHzBsnX/5gWnPbo7Sufsr5BdKYo9O1mGYgowpXU2NpGJ/OKC+m14b2JLWY4pYlYNlBk0/V",
	"ZLIoXHTOkeLKD540cmGWZFMh4Dt+9dGfHR1QFB2exmuOTx4332Lc3R56lLy9xTnrOV93BumiKxfxwaFK",
	"cTPHm9ywPXB5KXXTDe5HXsvC+ZtcTqCXTVZjA4UA/pMxdcVUpV0Rbat4qhmollNalkxoVBDnsnKJ/PAQ",
	"8YwL8vL8cDRwTyXDKWZUxadqakyJrzF73SSrg+4eHaWimonfufn38K+RYFEk4th/JseVklMOeFOFg6+f",
	"bW7e3NyMmp27D0D7Re7BzPeOD/WIPGf+fq8kEGHC15kCPoQ2tCic1SryyP4GbuYbbtCSN5LyB8NBwTMm",
	"NFCiW8ZeCQVddkZbyflT+Hkk1WTT9dWbvxzuH7w+PdiwfSJHWzzuYDi4ZkrjIrdHW9hSlkzYH58NHo22",
	"RjvwUKiZAslsXm9v0pJv9j0AC07Bg9Mz4m/3b9qu4do9VG+HW/OKWW3rD6YkOHStBfgeYmjvieW1lvOM",
	"iC/hZtFaPzzw/uXBmbtueXx0evbeh+iwRqmLLeKNjNZwhuoPegj3bJgruz8CL1oij+MlPL0V6s3TouhO",
	"cAC4wrEPc+y075+9re9+AJtoZUOG8vzALEPpPzBX3onn7XId21uQsWq7/qtCrdQRBjAmzf9g/ijR6PJO",
	"9PbWoidp68u7vK7JPnonTg1VLj5Ktl2ctT0xYqRcOLfw2uyC2V0Mmy+872xt3dnD7vWDxomX3U8reL99",
	"XBX1pekNhwxN4ueMu5sPXNWrbINfLKHsFUX97rGhEw25wFVpzxvgAF+CvnCpaIkICBCqJTzBbkLwAgjQ",
	"z6BLddhp3z0y7dTsH2U+XwGHTuahifJx2/4P9rY7tYVR3s/1o/crvvTc3Ys9WLPHM8Y98OBCXKxWCFye",
	"U4titlNR4c7utrcNcQe3Ld0b3Qt3re54HPO1GRXg0vM8Jzx/PbL8tMk0N8dcpPVdAGV/hXKSlDvrz6l7",
	"SS4FrTP/sItr2aSOF1zge/0/zl1EZSFnio0b/2556my7sZq7kjjkQb293Rm/HX16U+Ze6NRRVah90KKo",
	"5JZ4qvIYdan6G+GWSZO4lhBDl6Y+8fwzoqRgJvlajf3uco7cU/69/AQb1/yksWmPb3XMEOTKx2wtpWLC",
	"zNBdW/DJQDCYy/j0TBQcf1SEZSe1C9AthuT98bn9H+gYzw9+OTg7iLQMXRdDjnSNvlmsrXNgiMJQXuCM",
	"2+tYIgy8CjK4b5F6C3HqlxIm3ySSl8ysTCELedieizjHhjuWzIvQBkzN7n7N08DmXsrRGmpLWaVygIEM",
	"Vjxt2Ph20vsLtwuHzoPMbV0FXyZxd27FCnDQO5K4gaQAWEPa9j0L/0UmCrz6/i2bKO0JpvjDKWLmbxPl",
	"WzFRYEPuwETpbH6PiaI9AaSOniuXdDsTBWfQZ6LAr/fE5BB2v1nhcPO1zQq/5MWYXt2swK1LMLrVzApo",
	"u9ysWNqra2LAQlczMRCcfyv2r2hb7G5/mW3RS6xLbIul+xLIzJFdTW4X6wDqUtetDIw+boCNa25wlwbG",
	"agfuXg0Mt+y/uIHRt3legRjct0D8EgPDTz5lYKxGIbc1MGq0fW0Do2/DsPGfInuDgeGk79c1MO5C9gaS",
	"AmCjHs6Ibphk6cPgvoGcLc+XF1IXDEUOn98dDSUVud7JNclnL0f34Zm8TxJqj5IgJlfKJk4kuT0BtWim",
	"Fxf9tJM2UnsALSKbzU/wv8PFAvaEzeQ1gzofCB2ir+ktw7aArxdKztYWtH3qx+I5dHycSR0kEWsGCemq",
	"yyLcxgP1Qe1dTa/kGLTOc7xlDzMGqOxuzlPHTA2b3R42PZ7b7LUPcb0N6yEtJj2o6ppNqRCsuHPXCADf",
	"R+DftIukZ6JJTSdu+7fL5BtymcQbcxeukz6i6HOhNI9SJCjwIQD3S4f93can0phar28lbnVfel5jjAW+",
	"liYyv7rPpYWKFbdmDSdMY/NH/SwWnDKbtJjISidk+gtrfbsXA10XuHVRTCScS9uph7Gt1jXhpolx8+N8",
	"z01tCWOra9T7yHDAYYpD2OZr+W86fAweSK1L8sXL7BkTV9E/pC+PrPkEiiVnidrIX49jJbkVS2mmq210",
	"Uk1tkvvF2mCXkHU6zfWFFe8OcB3/7qPhRNOlNLtuFsNK5POVXI73TSoJfK7N/VJg+knhdo7BJSLNOQg7",
	"Iu1OHYW3kxL36zls4uWv7kFcsstt/Xrwpx6pVT2LrUUlPYy3I61buxw7eL5Pt9EJszpexFg7KkHbGSHY",
	"zS2OcpLFLR/8TpS92usXz7ul6EEG14KatF9oTbcq937L9nTfVNMnvtH6b5v6W7Kpe6szf6lx3UshveZ1",
	"63TFB7uVOnknJnZzgv1GdqPdvZnZzVEWGdotxH59U7uNkJW3aR1zu0kMC/lwTx7ECxfobtcGdwouVIfz",
	"D3AtTLbWJVze8W2hFhidsXfinYB6IFhhPHofv2qG2k+P34m940OouS4MYR8t08UXhqWZRl2NjApR9dhF",
	"beQvdo/31JZfYA6tYbF3oMfoTA1Rvyz255lZS89ZOlq0iBBudwTWIs9F1H9Lc2wZ+/MGWZf93a1Jdmtu",
	"cs9mWQs/f3nDbNl+dxW1wTdxEFcwz9pLSxtotya02xtpXZzfkZlGTZa4xntsP7uaMOscdej3zSg6UIqV",
	"FuE5BO0q+mC1VFh6fbq+KCOgL+gN+Eg+C7MyyayewrN0d1wyz7eyPXWCT+elma+b6nNfemjkCWiMMFoq",
	"hTezZc/JLpRQwu46i/QLWjvsrU7ce7nJtu+TUFY09TsGFBsrpqe9IgYgWt1VMaM4u2balad25Bs/jxvK",
	"ebUUmin1L15aQBkVRMhiDkYLhSLnyC7dS+vJJ226950iRH89KRWP2u+i70+lWYbCryGUPLXcs8vwpadm",
	"03xEObGZ2LC9o3fP207YJDFWYh9PVk42+9MobbH8WoD8O+KRNdCG0uleLl3OKPFZqESCotV57cylIjmj",
	"/i+aEsbrWb61UXpfuZXR1J8vmfoKAh4f7fqiy/3aWbLxJYfGQ15r3F6InxBLEWR45ss9JmbkneZqroHb",
	"W1D46lQXEXZPhaQvCgGc62/b79+aX0oyn+u/Pfzfkoe/XfPry9z6bQLo8eX7smCpHJUvcdrD8H2e+nN9",
	"b2YRgO73ySNWvrYj3q13IY5X97jDlo06DK7Htw7uUCgOdjWvXxuRijBX3HKhQ31Rx3finTjyXnU4UE3f",
	"uvcFJN3jDiULeU9POceeBDO1vlscV7Icuq/09+d4wvtIeoH7e8l+e0L0uWg9wnY5qA4NusKsm2Vv5dGE",
	"nLTY3zs+1MjeAYB76ccVCgWWUkHJYo612TU3lXuyCJ/9ilpj3v1EGsPAu5HmXoeuqKzuVJWFd0NcKXio",
	"nT2rhC9w7iuVumc08tbPfWkWfjBfkPWkrl97X0ywXWc3QUCHibq6a9lT7Yc2hXtGTQpHIhAdiwsc2lPe",
	"vC8RJuFnSiLkeEKlQor5TIKWvdhzdxQrWK0at3RsORMlOmbdOFZUtrSdIKNRUwqIvM8ti2v2Js3dnpq9",
	"t9itrmE6HDzGhql5BoCb52KvMlOp+B8sX7K3zfkO3QaoFfe3KxHVcg7RZUm3Crr1qC/YNqgvdxleW0VH",
	"uNc4Gi75Lx4869k3Z+0M/jwpvTQ25maeCogtIA0q5h1l/ZbuxoC6r301umfPsO2fYCqEsAkaC183VvLl",
	"pkIgKXwhIckPF+pnLa4Sp8l4l1GL9Yba+OFBthkzU+m9HqNlij70vXe33z4+a4+vTdXSvGWgQqOvIPBx",
	"oFohRFGeulmN076F1N9ZVepv30bq12YuTjDCVy3W58tpF19USO1NmnT7HNKrEi72/+uQLbzgUyp2zQuW",
	"T1juDKHkiuBRZO8g6Geot/RY340DGtYDfA2RH2+9d+jepUq7NnHbTo++6EQ4bq49mtfk5p0T4QC1lW1f",
	"I/7tBajdTF17OsUa5J+wevvnZ5ubn3I5o1x8fvaplMp8HnQ25fgQgugwtWuqOL1yoQnsiMgGl+rgGT65",
	"NZXAhJpwsHV9uQsgggdRmSaMH7Z+2Op0t826nX0R+rg71J9vd//p7OyYlEoamcmCuG6f4Wy5LfgUO4w6",
	"/eFZC3zbTZG940Mo/O9LSXWDFO2YciuO5R+JawNy1RJSZUV6uviiDamSGz1dYouqyyfrMARHt7FvHaXr",
	"xFOO6HYJMPaRZZV/zwj30Xf2r0PjO6RMzbjWrYFqgbH2MCuO0Ll50jkHOqDUyPb1xM8Xn/9vAAAA///6",
	"zjYb/doAAA==",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
